# Generated by Django 3.1 on 2020-10-06 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200812_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mypage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('p1', models.CharField(max_length=40, null=True)),
                ('p2', models.CharField(max_length=40, null=True)),
                ('relationship', models.CharField(max_length=20, null=True)),
                ('image_path', models.CharField(max_length=150)),
                ('regi_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='department',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='position',
        ),
        migrations.AlterField(
            model_name='access',
            name='enter_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 10, 40, 13, 618764)),
        ),
        migrations.AlterField(
            model_name='access',
            name='recent',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 10, 40, 13, 618764)),
        ),
    ]
